## Aim : bingo card proposal for flowers
## Author : Brittany Lopez Barreto
c(
  "Lily",
  "Rose",
  "Carnation",
  "Baby's Breath",
  "Orchid",
  "Marigold",
  "Sunflower",
  "Hydrangea",
  "Tulip",
  "Peony",
  "Daisy",
  "Alstromeria",
  "Lavender",
  "Hibiscus",
  "Birds of Paradise",
  "Moonflower",
  "Pansy",
  "Hyacinth",
  "Petunia",
  "Poppy",
  "Snapdragon",
  "Violet",
  "Cosmos",
  "Calendula",
  "Azalea",
  "Begonia"
)
