#Types of dogs
c(
  "American Cocker Spaniel",
  "Australian Shepard",
  "Australian Terrier",
  "Basset Hound",
  "Beagle",
  "Bernese Mountain Dog",
  "Border Collie",
  "Boston Terrier",
  "Bulldog",
  "Cairn Terrier",
  "Cavalier King Charles Spaniel",
  "Chihuahua",
  "Dachshund",
  "Dalmatian",
  "Doberman Pinscher",
  "French Bulldog",
  "German Shepherd",
  "Golden Retriever",
  "Great Dane",
  "Greyhound",
  "Irish Setter",
  "Labrador Retriever",
  "Maltese",
  "Newfoundland",
  "Norwegian Elkhound",
  "Norwich Terrier",
  "Old English Sheepdog",
  "Papillon"
)
