c("Can you see my screen?",
  "Can you hear me?",
  "Could everyone mute their phones?",
  "Someone forgets they are on mute",
  "I'm getting an echo",
  "Laggy screen",
  "Who just joined?",
  "Background noise",
  "Making a mistake in the dial-in code",
  "Someone in the room mutes to talk over the call",
  "Starting late",
  "Running over",
  "Small talk",
  "Someone randomly joins the wrong call",
  "People start talking at the same time",
  "Someone loses the connection and re-joins",
  "Hold music",
  "Bad signal",
  "Let's do a round of introductions",
  "Someone in a car",
  "Dog barking",
  "Crying baby",
  "Siren in the background",
  "Circle back on that",
  "Take this offline",
  "Hard stop",
  "Switching between calls",
  "Someone takes another call and forgets to mute",
  "Keyboard sounds",
  "Moves the microphone",
  "Someone is eating", 
  "Someone coughs directly into the microphone"
  )
