# Indiana Geology themed bingo
c("normal fault",
  "crystal lattice",
  "beer",
  "fold-thrust fault",
  "generic carbonate",
  "exposure",
  "brachiopod",
  "trilobite",
  "marine facies",
  "geode",
  "pyrite",
  "anticline",
  "syncline",
  "shale",
  "coal seam",
  "horn coral",
  "bryozoan",
  "karst",
  "till",
  "glacial outwash",
  "quaternary sediment",
  "roadcut"
  "quartz vug",
  "calcite vug",
  "stromatolite"
)
