# Iowa related things
c("corn",
  "grinnell",
  "raygun",
  "I-80",
  "state fair",
  "Traveler's umbrella",
  "American Gothic",
  "Is this heaven?",
  "Zombie Burger",
  "Local foods",
  "Schnitzelbank",
  "RAGBRAI",
  "Jordan Creek Mall",
  "Hy-Vee",
  "Hawkeyes",
  "Cyclones",
  "Go West",
  "Clear Lake",
  "75% vowels, 100% Awesome",
  "Idiots out...",
  "John Deere",
  "John Wayne",
  "Hawkeye vodka",
  "Toppling Goliath",
  "Dari Barn",
  "Dairy Zone",
  "Surf Ballroom",
  "Saint's Rest",
  "The Musicman",
  "Iowa's best burger"
)
