# Common phrases and notation (good or bad) in math proofs
# Submitted by Stephanie Reinders
c("Let ... ",
  "Let epsilon be given",
  "Greek letters",
  "For each",
  "For all",
  "There exists",
  "Clearly",
  "Obviously",
  "Therefore",
  "Moreover",
  "Hence",
  "Thus",
  "So",
  "QED",
  "w.l.o.g.",
  "w.r.t.",
  "proof without words",
  "variables with subscripts",
  "variables with subscripts with subscripts",
  "variables with subscripts, superscripts, and hats",
  "e used as a variable",
  "necessary and sufficient",
  "Theorem",
  "Corollary",
  "by definition",
  "proof by induction",
  "proof by contrapositive",
  "proof by contradiction"
)
