## Aim : bingo card proposal for animals
## Author : Larissa Stanberry
c('cat',
  'dog',
  'snapping turtle',
  'painted turtle',
  'muskrat',
  'mallard duck',
  'chipmunk',
  'squirrel',
  'deer',
  'cardinal',
  'red-winged blackbird',
  'blue jay',
  'swan',
  'deer',
  'monarch butterfly',
  'snake',
  'bee',
  'loon',
  'owl',
  'woodpecker',
  'wasp yellow jacket',
  'northern cardinal',
  'eagle',
  'hawk')
