# "olympic sports" past and present word bank - source https://en.wikipedia.org/wiki/Olympic_sports

c(
  "Diving",
  "Marathon swimming",
  "Swimming",
  "Synchronized swimming",
  "Water polo",
  "3-on-3 basketball",
  "Basketball",
  "Canoe/kayak (sprint)",
  "Canoe/kayak (slalom)",
  "BMX freestyle",
  "BMX racing",
  "Mountain biking",
  "Road cycling",
  "Track cycling",
  "Gymnanastics - Artistic",
  "Gymnanastics - Rhythmic",
  "Gymnanastics - Trampoline",
  "Volleyball (beach)",
  "Volleyball (indoor)",
  "Equestrian / Dressage",
  "Equestrian / Eventing",
  "Equestrian / Jumping",
  "Freestyle wrestling",
  "Greco-Roman wrestling",
  "Archery",
  "Athletics",
  "Badminton",
  "Baseball",
  "Boxing",
  "Fencing",
  "Field hockey",
  "Football",
  "Golf",
  "Handball",
  "Judo",
  "Karate",
  "Modern pentathlon",
  "Rowing",
  "Rugby sevens",
  "Sailing",
  "Shooting",
  "Skateboarding",
  "Softball",
  "Sport climbing",
  "Surfing",
  "Table tennis",
  "Taekwondo",
  "Tennis",
  "Triathlon",
  "Weightlifting",
  "Equestrian / Vaulting",
  "Handball / Field Handball",
  "Rugby / Rugby union",
  "Basque pelota",
  "Cricket",
  "Croquet",
  "Lacrosse",
  "Jeu de paume",
  "Polo",
  "Rackets",
  "Roque",
  "Tug of war",
  "Water motorsports",
  "Figure skating",
  "Ice hockey",
  "Figure skating",
  "Speed skating",
  "Short track speed skating",
  "Curling",
  "Cross-country skiing",
  "Alpine skiing",
  "Ski jumping",
  "Nordic combined",
  "Freestyle skiing",
  "Snowboarding",
  "Biathlon",
  "Luge",
  "Bobsleigh",
  "Skeleton",
  "Biathlon / Military Patrol"
)
