#' The agony of other people's data.

c(
  "duplicate rows",
  "website maze",
  "session has timed out",
  "broken formula",
  "mystery column",
  "metadata mixed with data",
  "out of date docs",
  ".XLSB",
  "assumed knowledge",
  "non-standard country names",
  "blank rows",
  "hidden cells",
  "circular references",
  "split cells",
  "long fieldnames are long",
  "metadata at end of spreadsheet",
  "arcane codes",
  "please enable macros",
  "colour as data",
  "merged cells",
  "acronym WTF?",
  "starred numbers*",
  "PDF tables",
  "numbers formatted as text",
  "metadata expressed as fieldnames",
  "fieldname EDA",
  "regex-driven workflow",
  "named region non-sequiturs",
  "password-protected files"
)
