# Seabirds themed bingo

c("Southern Royal Albatross",
  "Northern Royal Albatross",
  "Southern Giant Petrel",
  "Northern Giant Petrel",
  "Wandering Albatross",
  "Yellow-Nosed Albatross",
  "Black-Browed Albatross",
  "Sotty Albatross",
  "White-Chinned Petrel",
  "Westland Petrel",
  "Antartic Petrel",
  "Sooty Shearwater",
  "Atlantic Petrel",
  "Great Shearwater",
  "Cape Petrel",
  "Gray Petrel",
  "Little Shearwater",
  "Magnificient Frigatebird",
  "Neotropic Cormorant",
  "Rock Cormorant",
  "Olrog Gull",
  "Kelp Gull",
  "Magellanic Penguin",
  "Rockhopper Penguin")
