# Statistical ecology themed bingo
c("population dynamics",
  "life history",
  "state-space model",
  "Bayesian",
  "Poisson",
  "binomial",
  "species",
  "R (software)",
  "collaboration",
  "environmental drivers",
  "animal behavior",
  "genetic diversity",
  "reproductive success",
  "model selection",
  "survival probability",
  "life stage",
  "density dependence",
  "reproducible research",
  "regression",
  "R-squared",
  "mixed effects",
  "manuscript",
  "noisy data",
  "hierarchical model",
  "conference",
  "sample design",
  "p-value problem",
  "statistical significance",
  "statistical significance vs. scientific significance",
  "confidence interval",
  "beta regression on proportions",
  "ecological network",
  "bipartite network",
  "interaction network",
  "Lotka-Volterra equations",
  "exponential growth",
  "generalized linear model",
  "logistic regression",
  "heteroscedastic"
)
