# Statistical ecology themed bingo
c("population dynamics", 
  "life history", 
  "state-space model", 
  "Bayesian", 
  "Poisson", 
  "binomial", 
  "species", 
  "R (software)", 
  "collaboration", 
  "environmental drivers", 
  "animal behavior", 
  "genetic diversity", 
  "reproductive success", 
  "model selection", 
  "survival probability", 
  "life stage", 
  "density dependence", 
  "reproducible research", 
  "regression", 
  "R-squared", 
  "mixed effects", 
  "manuscript", 
  "noisy data", 
  "hierarchical model", 
  "conference",
  "sample design"
)