c(
  "Recieved e-mail from Robert Goodman",
  "Went to coffee cart",
  "Somehow lost 3 hours writing emails",
  "Went to dining center and it's closed",
  "Stomach grumbled in middle of class",
  "Went to the gym & it was too crowded",
  "Accidentally skipped meal because stuck in the lab",
  "Troubleshot code for 2+ hours",
  "Skipped class",
  "Did homework, ignored research",
  "Office hours, no one showed up",
  "Got lunch with grad students",
  "Went to trivia night at Kewl Cats",
  "Got Little Oven",
  "Went to lab meeting",
  "Ate at food trucks",
  "Free coffee at seminar",
  "Took the bus",
  "Gave up on Rscript for Bingo",
  "Procrastinated",
  "Took nap",
  "Got ignored by Grad Div",
  "Heard undergrad's complaining",
  "Looked for fellowship/funding",
  "Go to the pub",
  "Went to sleep after 2am",
  "Watched Netflix"
)