# Things you expect to encounter in useR conference
# Authors (GitHub handles):
# bearloga, corynissen, rmflight, Luke4130, barryrowlingson, hrbrmstr, spholmes,
# trestletech, daroczig, kylehamilton, petestmarie, yanlesin
c(
  "R vs. Python",
  "hadleyverse",
  "pipe",
  "A slide with a cat on it",
  "rmarkdown",
  "shiny",
  "bookdown",
  "grammar of",
  "R inferno",
  "%>%",
  "CRANdalf",
  "RConsortium",
  "mtcars",
  "diamonds",
  "Hadleyverse",
  "ArrCeePeePee",
  "cats",
  "kittens",
  "StackOverflow",
  "Data Science",
  "rainbow",
  "pie chart",
  "SAS",
  "SPSS",
  "Excel",
  "R4",
  "R5",
  "R6",
  "Splus",
  "Tibco",
  "R-forge",
  "library!=package",
  "%<>%",
  "sell out",
  "cloud",
  "language war",
  "Julia",
  "R-bloggers",
  "analytics",
  "docker",
  "A failed live demo",
  "two people exchanging business cards",
  "in the cloud",
  "AWS",
  "A laptop with > 5 R themed stickers",
  "A t-shirt from a past R conference",
  "Microsoft Windows running on a PC",
  "Somebody coding in emacs / vi",
  "spark / sparkr",
  "notebook",
  "repo",
  "base (as in base vs ggplot2)",
  "virtually every dplyr verb",
  "literate",
  "sankey",
  "contour",
  "flowchart",
  "reproducible",
  "interactive",
  "stata",
  "structural equation",
  "credible",
  "big data",
  "subversion",
  "cloud scale",
  "Beamer slides",
  "GitHub",
  "CRAN",
  "install",
  "development",
  "version",
  "bug(fix)",
  "devtools",
  "roxygen",
  "Rcpp",
  "benchmark",
  "profiling",
  "is that Hadley Wickham?",
  "Bayesian"
)
