c("serpentinite",
  "metabasalt",
  "franciscan",
  "melange",
  "metasandstone",
  "metaschist",
  "metachert",
  "alluvium",
  "landslide",
  "folding",
  "faulting",
  "anticline",
  "syncline",
  "shale",
  "geomorphology",
  "subduction",
  "great valley group",
  "siliciclastic",
  "ophiolite",
  "coast ranges",
  "quaternary deposits",
  "high-grade metamorphism",
  "graywacke",
  "Miocene",
  "stream terraces"
)
