#Native PLants of California (Go pollinitors!)
c("Sticky Monkey Flower",
  "Yarrow",
  "Valley oak",
  "Live oak",
  "California poppy",
  "California fuchsia",
  "Hummingbird sage",
  "California coffeeberry",
  "Manzanita",
  "Sequoia sempervirens",
  "Penstemons",
  "Bush anemone",
  "Blue-eyed grass",
  "Cholla",
  "Milkweed",
  "Coastal prickly pear",
  "Matilija poppy",
  "Douglas iris",
  "Island alum root",
  "Dudleya",
  "Mountain violet",
  "Silver Lupine",
  "Buckwheat",
  "California gooseberry",
  "Ceanothus",
  "Coyote Bush",
  "Chaparral mallow",
  "Coffeeberry",
  "Deergrass",
  )
