#Eurovision Bingo (for usein the grand final, because certain cells pertain to voting results)
c("Costume change/reveal",
  "Multilingual song",
  "Wink at camera",
  "Pyrotechnics",
  "Fog machine",
  "Background interpretive dancers",
  "Dramatic high note",
  "Sparkle/sequin outfit",
  "Crazy hair/hat",
  "Voice crack",
  "Dance break",
  "Song not in English",
  "Hair flip",
  "Awkward green room interview",
  "Hosts are cringy",
  "Seizure inducing lights",
  "Wind machine",
  "Dramatic solo ballad",
  "Dizzying LED backdrop",
  "Someone cries",
  "Shirtless male dancers",
  "Song has vague uplifting message",
  "Flag waved at camera",
  "Leather pants",
  "Synchronized dance routine",
  "Country outside of Europe performs",
  "Previous contestant makes an apperance",
  "Obviously fake instruments on stage",
  "Clapping during a song",
  "Love song",
  "Technical difficulties",
  "'Heart hands' to the camera",
  "Huge props")
