##Soccer
c("Yellow Card withing first ten minutes",
  "Announcers roast each other",
  "Transfer News",
  "Sending off",
  "Goal from outside the box",
  "Player dives",
  "Ball hits the ref",
  "Goalkeeper gets a yellow",
  "Added time exceeds 3 minutes",
  "Announcers apologize for crowds rude chants",
  "VAR Penalty Check",
  "Missed penalty",
  "goal from a set piece",
  "Handball",
  "More than 5 offsides",
  "Manager receives a yellow card",
  "Keeping the ball in the corner",
  "Goal disallowed",
  "Pitch Invasion",
  "Not all subs are used",
  "Fight breaks out",
  "Comment on position in the league table",
  "Advertising for upcoming games",
  "Headed Goal",
  "Head injury"
)
